"""add is_banned to users

Revision ID: 6140b794a2bc
Revises: 002_provider_fields
Create Date: 2026-05-23 12:23:37.074790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6140b794a2bc'
down_revision: Union[str, Sequence[str], None] = '002_provider_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedback_agent_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               comment='Auto-generated from the first user message',
               existing_comment='Auto-generated from first user message, or manually set by user',
               existing_nullable=True)
    op.alter_column('conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='False for archived or closed conversations',
               existing_nullable=False)
    op.alter_column('conversations', 'current_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment="'groq' or 'ollama' — which backend is currently active",
               existing_nullable=False)
    op.alter_column('conversations', 'provider_switched',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True if an automatic fallback from Groq to Ollama occurred',
               existing_nullable=False)
    op.alter_column('models', 'provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment="'groq' or 'ollama'",
               existing_nullable=False)
    op.alter_column('models', 'ollama_model_id',
               existing_type=sa.VARCHAR(length=150),
               comment="Exact model string sent to Ollama API, e.g. 'llama3.2'",
               existing_nullable=True)
    op.alter_column('models', 'description',
               existing_type=sa.TEXT(),
               comment='Shown to users in the model selection UI',
               existing_comment='Shown to users in the model selection dropdown',
               existing_nullable=True)
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.alter_column('models', 'description',
               existing_type=sa.TEXT(),
               comment='Shown to users in the model selection dropdown',
               existing_comment='Shown to users in the model selection UI',
               existing_nullable=True)
    op.alter_column('models', 'ollama_model_id',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="Exact model string sent to Ollama API, e.g. 'llama3.2'",
               existing_nullable=True)
    op.alter_column('models', 'provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'groq'::character varying"),
               comment=None,
               existing_comment="'groq' or 'ollama'",
               existing_nullable=False)
    op.alter_column('conversations', 'provider_switched',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='True if an automatic fallback from Groq to Ollama occurred',
               existing_nullable=False)
    op.alter_column('conversations', 'current_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'groq'::character varying"),
               comment=None,
               existing_comment="'groq' or 'ollama' — which backend is currently active",
               existing_nullable=False)
    op.alter_column('conversations', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='False for archived or closed conversations',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               comment='Auto-generated from first user message, or manually set by user',
               existing_comment='Auto-generated from the first user message',
               existing_nullable=True)
    op.create_table('message_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint("rating::text = ANY (ARRAY['up'::character varying, 'down'::character varying]::text[])", name=op.f('ck_feedback_rating')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('message_feedback_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_feedback_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_feedback_pkey'))
    )
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_feedback_agent_id'), 'message_feedback', ['agent_id'], unique=False)
    # ### end Alembic commands ###